# Config for the Gemini Pull Request Review Bot.
# https://github.com/marketplace/gemini-code-assist
have_fun: false
code_review:
  disable: false
  comment_severity_threshold: HIGH
  max_review_comments: -1
  pull_request_opened:
    help: false
    summary: true
    code_review: true
ignore_patterns:
  [
    'docs/assets/**',
    'docs/ref/**',
    'assets/**',
    'user_testing/**',
    'prompt-*.md',
    '**/*.png',
    '**/*.jpg',
    '**/*.jpeg',
    '**/*.gif',
    '**/*.svg',
    '**/*.ico',
    '**/*.mp3',
    '**/*.wav',
    '**/*.mp4',
    '**/*.mov',
    '**/*.avi',
    '**/*.pdf',
    '**/*.zip',
    '**/*.tar.gz',
    '**/*.rar',
    'node_modules/**',
    '.git/**',
    'dist/**',
    'build/**',
    'coverage/**',
    '.next/**',
    '.nuxt/**',
    '.output/**',
  ]
